version: "3.9"
services:
  db:
    image: mysql
    platform: linux/x86_64 # used for apple silicon M1
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root # testing purpose
    volumes:
      - /tmp/mysql-database:/data/db
      - ./config/init.sql:/data/application/init.sql
    ports:
      - 3306:3306
  scraper:
    container_name: scraper_service
    platform: linux/x86_64
    image: scraper-service:1.0.0
    build:
      context: ./scraper
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped