version: "3.9"
services:
  db:
    image: mysql
    platform: linux/x86_64 # used for apple silicon M1
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root # testing purpose
    volumes:
      - /tmp/mysql-database:/data/db
      - ./config/init.sql:/data/application/init.sql
    ports:
      - 3306:3306